name: Unzip uploaded archives and commit

on:
  push:
    paths:
      - '**/*.zip'
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Unzip all archives into repo root
        run: |
          shopt -s nullglob
          for f in **/*.zip; do
            echo "Processing $f"
            TMPDIR=$(mktemp -d)
            unzip -o "$f" -d "$TMPDIR"
            cp -a "$TMPDIR"/. .
            rm -rf "$TMPDIR"
          done
          echo "Finished unzipping."

      - name: Commit & push changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A
          if git diff --
